services:
  - type: web
    name: moviematch
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: TMDB_API_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///instance/moviematch.db
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1

databases:
  - name: moviematch-db
    databaseName: moviematch
    plan: free 