services:
  - type: web
    name: moviematch
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: moviematch-db
    databaseName: moviematch
    plan: free 