services:
  - type: web
    name: moviematch
    env: python
    buildCommand: |
      pip install -r requirements.txt
      export FLASK_APP=app.py
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: TMDB_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false

databases:
  - name: moviematch-db
    databaseName: moviematch
    plan: free 