"""Initial migration

Revision ID: 807f3a057073
Revises: 
Create Date: 2025-01-02 22:58:53.358094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807f3a057073'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preference', schema=None) as batch_op:
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
